version: "3.6"

services:

  pihole:
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '83:80/tcp'
    environment:
      TZ: 'Europe/Madrid'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - 'pihole_etc-pihole:/etc/pihole'
      - 'pihole_etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

volumes:
  pihole_etc-pihole:
  pihole_etc-dnsmasq.d:
