version: "3.6"

services:

  nginx:
    build:
      context: nginx
    hostname: pi_nginx
    volumes:
      - 'nginx_letsencrypt:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - host.docker.internal:host-gateway

  pihole:
    image: pihole/pihole:latest
    hostname: pi_pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '83:80/tcp'
    environment:
      TZ: 'Europe/Madrid'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - 'pihole_etc-pihole:/etc/pihole'
      - 'pihole_etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped


volumes:
  pihole_etc-pihole:
  pihole_etc-dnsmasq.d:
  nginx_letsencrypt:

networks:
  default:
    name: pi
